// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAazIeP66kwJqxA6nvVeS4WRhhUl0_HSv8',
    appId: '1:1025570772079:web:cfa16d88f239251c75e99a',
    messagingSenderId: '1025570772079',
    projectId: 'instagram-clone-20407',
    authDomain: 'instagram-clone-20407.firebaseapp.com',
    storageBucket: 'instagram-clone-20407.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR4JNmDlTCGVWHXWxqsDoHkMshWODiKxc',
    appId: '1:1025570772079:android:544e2e30ba4c340975e99a',
    messagingSenderId: '1025570772079',
    projectId: 'instagram-clone-20407',
    storageBucket: 'instagram-clone-20407.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp2AFVGGLhrpOagqq7IsXfmPEEwRxmiJE',
    appId: '1:1025570772079:ios:0ec857edd6bfb19c75e99a',
    messagingSenderId: '1025570772079',
    projectId: 'instagram-clone-20407',
    storageBucket: 'instagram-clone-20407.appspot.com',
    iosBundleId: 'com.shadyarbzharothman.instagramclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp2AFVGGLhrpOagqq7IsXfmPEEwRxmiJE',
    appId: '1:1025570772079:ios:d9efae10a231209275e99a',
    messagingSenderId: '1025570772079',
    projectId: 'instagram-clone-20407',
    storageBucket: 'instagram-clone-20407.appspot.com',
    iosBundleId: 'com.shadyarbzharothman.instagramclone.RunnerTests',
  );
}
